In [35]:
from IPython.core.interactiveshell import InteractiveShell

# Força o notebook a mostrar todas as saídas de uma célula, não só a última
InteractiveShell.ast_node_interactivity = "all"

In [1]:
# Install Hopsworks Python client
!pip install "hopsworks[python]"

Collecting hopsworks[python]
  Downloading hopsworks-5.0.6-py3-none-any.whl.metadata (12 kB)
Collecting pyhumps==1.6.1 (from hopsworks[python])
  Downloading pyhumps-1.6.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from hopsworks[python]) (2.31.0)
Collecting furl (from hopsworks[python])
  Downloading furl-2.1.4-py2.py3-none-any.whl.metadata (25 kB)
Collecting boto3 (from hopsworks[python])
  Downloading boto3-1.43.86-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: pandas<2.4.0 in /opt/conda/lib/python3.11/site-packages (from pandas[mysql]<2.4.0->hopsworks[python]) (2.0.3)
Collecting numpy<2.5.0,>=1.26.3 (from hopsworks[python])
  Downloading numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pyjks (from hopsworks[python])
  Downloading pyjks-20.0.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting mock (from hopsworks[python])
  Downloading mock-5.2.0-py3-none-any.whl.metadata (3.1 kB)
Collecting avro==1.12.0 (from hopsworks[python])
  Downloading avro-1.12.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting PyMySQL[rsa] (from hopsworks[python])
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting tzlocal (from hopsworks[python])
  Downloading tzlocal-5.4.4-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: fsspec<2025.12.0 in /opt/conda/lib/python3.11/site-packages (from hopsworks[python]) (2023.9.2)
Collecting retrying (from hopsworks[python])
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Collecting hopsworks_aiomysql==0.2.2 (from hopsworks_aiomysql[sa]==0.2.2->hopsworks[python])
  Downloading hopsworks_aiomysql-0.2.2-py3-none-any.whl.metadata (12 kB)
Collecting opensearch-py<=2.4.2,>=1.1.0 (from hopsworks[python])
  Downloading opensearch_py-2.4.2-py2.py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from hopsworks[python]) (4.66.1)
Collecting grpcio<2.0.0,>=1.49.1 (from hopsworks[python])
  Downloading grpcio-1.83.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.7 kB)
Collecting protobuf<5.0.0,>=4.25.4 (from hopsworks[python])
  Downloading protobuf-4.25.9-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from hopsworks[python]) (23.2)
Collecting hopsworks-apigen<2.0.0,>=1.0.4 (from hopsworks[python])
  Downloading hopsworks_apigen-1.0.5-py3-none-any.whl.metadata (189 bytes)
Requirement already satisfied: click>=8.1 in /opt/conda/lib/python3.11/site-packages (from hopsworks[python]) (8.1.7)
Collecting tomli-w>=1.0 (from hopsworks[python])
  Downloading tomli_w-1.2.0-py3-none-any.whl.metadata (5.7 kB)
Collecting build (from hopsworks[python])
  Downloading build-1.6.0-py3-none-any.whl.metadata (5.6 kB)
Collecting pyarrow>=17.0 (from hopsworks[python])
  Downloading pyarrow-25.0.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting confluent-kafka<=2.11.1 (from hopsworks[python])
  Downloading confluent_kafka-2.11.1-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting fastavro<=1.12.0,>=1.4.11 (from hopsworks[python])
  Downloading fastavro-1.12.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.7 kB)
Collecting hops-deltalake==1.4.0-post121 (from hopsworks[python])
  Downloading hops_deltalake-1.4.0.post121-cp310-abi3-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting httpx<=0.28.1 (from hopsworks[python])
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting arro3-core>=0.5.0 (from hops-deltalake==1.4.0-post121->hopsworks[python])
  Downloading arro3_core-0.8.1-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (515 bytes)
Collecting deprecated>=1.2.18 (from hops-deltalake==1.4.0-post121->hopsworks[python])
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: sqlalchemy<=2.0.41,>=1.3 in /opt/conda/lib/python3.11/site-packages (from hopsworks_aiomysql[sa]==0.2.2->hopsworks[python]) (2.0.22)
Requirement already satisfied: typing-extensions~=4.12 in /opt/conda/lib/python3.11/site-packages (from grpcio<2.0.0,>=1.49.1->hopsworks[python]) (4.16.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.11/site-packages (from httpx<=0.28.1->hopsworks[python]) (4.0.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.11/site-packages (from httpx<=0.28.1->hopsworks[python]) (2023.7.22)
Collecting httpcore==1.* (from httpx<=0.28.1->hopsworks[python])
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /opt/conda/lib/python3.11/site-packages (from httpx<=0.28.1->hopsworks[python]) (3.4)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.11/site-packages (from httpcore==1.*->httpx<=0.28.1->hopsworks[python]) (0.16.0)
Requirement already satisfied: urllib3>=1.26.18 in /opt/conda/lib/python3.11/site-packages (from opensearch-py<=2.4.2,>=1.1.0->hopsworks[python]) (2.0.7)
Requirement already satisfied: six in /opt/conda/lib/python3.11/site-packages (from opensearch-py<=2.4.2,>=1.1.0->hopsworks[python]) (1.16.0)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.11/site-packages (from opensearch-py<=2.4.2,>=1.1.0->hopsworks[python]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas<2.4.0->pandas[mysql]<2.4.0->hopsworks[python]) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas<2.4.0->pandas[mysql]<2.4.0->hopsworks[python]) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->hopsworks[python]) (3.3.0)
Collecting botocore<1.44.0,>=1.43.86 (from boto3->hopsworks[python])
  Downloading botocore-1.43.86-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3->hopsworks[python])
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3->hopsworks[python])
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Collecting packaging (from hopsworks[python])
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyproject_hooks (from build->hopsworks[python])
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Collecting orderedmultidict>=1.0.1 (from furl->hopsworks[python])
  Downloading orderedmultidict-1.0.2-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting javaobj-py3 (from pyjks->hopsworks[python])
  Downloading javaobj_py3-0.6.1-py2.py3-none-any.whl.metadata (31 kB)
Collecting pyasn1>=0.3.5 (from pyjks->hopsworks[python])
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Collecting pyasn1-modules (from pyjks->hopsworks[python])
  Using cached pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting pycryptodomex (from pyjks->hopsworks[python])
  Downloading pycryptodomex-3.23.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting twofish (from pyjks->hopsworks[python])
  Downloading twofish-0.3.0.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Collecting cryptography>=46.0.7 (from PyMySQL[rsa]->hopsworks[python])
  Downloading cryptography-50.0.1-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (4.3 kB)
Collecting cffi>=2.0.0 (from cryptography>=46.0.7->PyMySQL[rsa]->hopsworks[python])
  Downloading cffi-2.1.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.5 kB)
Collecting wrapt<3,>=1.10 (from deprecated>=1.2.18->hops-deltalake==1.4.0-post121->hopsworks[python])
  Downloading wrapt-2.4.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (7.4 kB)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.11/site-packages (from sqlalchemy<=2.0.41,>=1.3->hopsworks_aiomysql[sa]==0.2.2->hopsworks[python]) (3.0.0)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.11/site-packages (from anyio->httpx<=0.28.1->hopsworks[python]) (1.3.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=46.0.7->PyMySQL[rsa]->hopsworks[python]) (2.21)
Downloading avro-1.12.0-py2.py3-none-any.whl (124 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 kB 4.7 MB/s eta 0:00:00
Downloading hops_deltalake-1.4.0.post121-cp310-abi3-manylinux_2_28_x86_64.whl (48.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.3/48.3 MB 32.1 MB/s eta 0:00:0000:0100:01
Downloading hopsworks_aiomysql-0.2.2-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.2/44.2 kB 9.1 MB/s eta 0:00:00
Downloading pyhumps-1.6.1-py3-none-any.whl (5.0 kB)
Downloading confluent_kafka-2.11.1-cp311-cp311-manylinux_2_28_x86_64.whl (3.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 70.7 MB/s eta 0:00:0000:01:00:01
Downloading fastavro-1.12.0-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 58.4 MB/s eta 0:00:00a 0:00:01
Downloading grpcio-1.83.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (7.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 57.1 MB/s eta 0:00:0000:0100:01
Downloading hopsworks_apigen-1.0.5-py3-none-any.whl (19 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 7.9 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 14.1 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 56.8 MB/s eta 0:00:0000:0100:01
Downloading opensearch_py-2.4.2-py2.py3-none-any.whl (258 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.6/258.6 kB 53.3 MB/s eta 0:00:00
Downloading protobuf-4.25.9-cp37-abi3-manylinux2014_x86_64.whl (295 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.2/295.2 kB 66.6 MB/s eta 0:00:00
Downloading pyarrow-25.0.1-cp311-cp311-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 30.4 MB/s eta 0:00:0000:0100:01
Downloading tomli_w-1.2.0-py3-none-any.whl (6.7 kB)
Downloading boto3-1.43.86-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 32.7 MB/s eta 0:00:00
Downloading build-1.6.0-py3-none-any.whl (31 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 22.0 MB/s eta 0:00:00
Downloading furl-2.1.4-py2.py3-none-any.whl (27 kB)
Downloading hopsworks-5.0.6-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 45.3 MB/s eta 0:00:00
Downloading mock-5.2.0-py3-none-any.whl (31 kB)
Downloading pyjks-20.0.0-py2.py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 11.5 MB/s eta 0:00:00
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Downloading tzlocal-5.4.4-py3-none-any.whl (18 kB)
Downloading arro3_core-0.8.1-cp311-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 49.1 MB/s eta 0:00:00a 0:00:01
Downloading botocore-1.43.86-py3-none-any.whl (15.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 51.0 MB/s eta 0:00:0000:0100:01
Downloading cryptography-50.0.1-cp311-abi3-manylinux_2_34_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 58.4 MB/s eta 0:00:0000:0100:01
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading orderedmultidict-1.0.2-py2.py3-none-any.whl (11 kB)
Downloading pyasn1-0.6.4-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 19.2 MB/s eta 0:00:00
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 10.5 MB/s eta 0:00:00
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 25.5 MB/s eta 0:00:00
Downloading javaobj_py3-0.6.1-py2.py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.0/95.0 kB 27.6 MB/s eta 0:00:00
Using cached pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pycryptodomex-3.23.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 47.9 MB/s eta 0:00:00a 0:00:01
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading cffi-2.1.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (217 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.8/217.8 kB 40.6 MB/s eta 0:00:00
Downloading wrapt-2.4.0-cp311-cp311-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (217 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.8/217.8 kB 43.4 MB/s eta 0:00:00
Building wheels for collected packages: twofish
  Building wheel for twofish (setup.py) ... done
  Created wheel for twofish: filename=twofish-0.3.0-cp311-cp311-linux_x86_64.whl size=11601 sha256=3c894060dd99e742182b4df2b0fc05c68ea387dc65113d6879b171a64d3c59ce
  Stored in directory: /home/jovyan/.cache/pip/wheels/4f/0b/b1/d97875c8e719f4a31f39c3ea718798318be32cf0068b042351
Successfully built twofish
Installing collected packages: twofish, pyhumps, wrapt, tzlocal, tomli-w, retrying, pyproject_hooks, PyMySQL, pycryptodomex, pyasn1, pyarrow, protobuf, packaging, orderedmultidict, numpy, mock, jmespath, javaobj-py3, httpcore, hopsworks-apigen, grpcio, fastavro, confluent-kafka, cffi, avro, arro3-core, pyasn1-modules, opensearch-py, httpx, hopsworks_aiomysql, furl, deprecated, cryptography, build, botocore, s3transfer, pyjks, hops-deltalake, boto3, hopsworks
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 13.0.0
    Uninstalling pyarrow-13.0.0:
      Successfully uninstalled pyarrow-13.0.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.24.3
    Uninstalling protobuf-4.24.3:
      Successfully uninstalled protobuf-4.24.3
  Attempting uninstall: packaging
    Found existing installation: packaging 23.2
    Uninstalling packaging-23.2:
      Successfully uninstalled packaging-23.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
  Attempting uninstall: cffi
    Found existing installation: cffi 1.16.0
    Uninstalling cffi-1.16.0:
      Successfully uninstalled cffi-1.16.0
  Attempting uninstall: cryptography
    Found existing installation: cryptography 41.0.4
    Uninstalling cryptography-41.0.4:
      Successfully uninstalled cryptography-41.0.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyopenssl 23.2.0 requires cryptography!=40.0.0,!=40.0.1,<42,>=38.0.0, but you have cryptography 50.0.1 which is incompatible.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 2.4.6 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.4.6 which is incompatible.
scikit-learn 1.3.1 requires numpy<2.0,>=1.17.3, but you have numpy 2.4.6 which is incompatible.
scipy 1.11.3 requires numpy<1.28.0,>=1.21.6, but you have numpy 2.4.6 which is incompatible.
contourpy 1.1.1 requires numpy<2.0,>=1.16; python_version <= "3.11", but you have numpy 2.4.6 which is incompatible.
Successfully installed PyMySQL-1.2.0 arro3-core-0.8.1 avro-1.12.0 boto3-1.43.86 botocore-1.43.86 build-1.6.0 cffi-2.1.1 confluent-kafka-2.11.1 cryptography-50.0.1 deprecated-1.3.1 fastavro-1.12.0 furl-2.1.4 grpcio-1.83.1 hops-deltalake-1.4.0.post121 hopsworks-5.0.6 hopsworks-apigen-1.0.5 hopsworks_aiomysql-0.2.2 httpcore-1.0.9 httpx-0.28.1 javaobj-py3-0.6.1 jmespath-1.1.0 mock-5.2.0 numpy-2.4.6 opensearch-py-2.4.2 orderedmultidict-1.0.2 packaging-26.3 protobuf-4.25.9 pyarrow-25.0.1 pyasn1-0.6.4 pyasn1-modules-0.4.2 pycryptodomex-3.23.0 pyhumps-1.6.1 pyjks-20.0.0 pyproject_hooks-1.2.0 retrying-1.4.2 s3transfer-0.19.2 tomli-w-1.2.0 twofish-0.3.0 tzlocal-5.4.4 wrapt-2.4.0

In [ ]:

# Read data from the feature group
df = fg.read()
print(f"Connected to {project.name}. Feature group has {len(df)} rows")

# For model serving
ms = project.get_model_serving()

# For model registry
mr = project.get_model_registry()

In [3]:
!pip install "numpy<2.0.0"

Collecting numpy<2.0.0
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [1]:
# Connect to Hopsworks
import hopsworks

In [3]:
project = hopsworks.login(
    project='my_first_project10',  # Replace with your project name
    host="eu-west.cloud.hopsworks.ai",
    port=443,
    api_key_value="sJp2D6ugWVGGEVdR.yHQXIlt2VDmShUYtdZ05OimwLYCoph0mMDzN8PigKJnlB1VwjqWlhbA7gkhYDaEq"  # Get from Hopsworks UI > Account Settings > API Keys
)

2026-09-02 17:10:38,962 INFO: Closing external client and cleaning up certificates.
2026-09-02 17:10:38,962 INFO: Connection closed.
2026-09-02 17:10:38,963 INFO: Initializing external client
2026-09-02 17:10:38,964 INFO: Base URL: https://eu-west.cloud.hopsworks.ai:443
2026-09-02 17:10:41,542 INFO: Python Engine initialized.

Logged in to project, explore it here https://eu-west.cloud.hopsworks.ai:443/p/42213

In [4]:
# Access the feature store
fs = project.get_feature_store()

In [6]:
fs.__dict__

{'_id': 30898,
 '_name': 'my_first_project10_featurestore',
 '_created': '2026-08-21T11:27:29.000Z',
 '_project_name': 'my_first_project10',
 '_project_id': 42213,
 '_online_feature_store_name': 'my_first_project10',
 '_online_feature_store_size': None,
 '_offline_feature_store_name': 'my_first_project10_featurestore',
 '_online_enabled': True,
 '_num_feature_groups': 0,
 '_num_training_datasets': 0,
 '_num_storage_connectors': 4,
 '_num_feature_views': 0,
 '_feature_group_api': <hsfs.core.feature_group_api.FeatureGroupApi at 0x7fa3f0ba0310>,
 '_storage_connector_api': <hsfs.core.storage_connector_api.StorageConnectorApi at 0x7fa3f3485690>,
 '_training_dataset_api': <hsfs.core.training_dataset_api.TrainingDatasetApi at 0x7fa3f0b82cd0>,
 '_feature_group_engine': <hsfs.core.feature_group_engine.FeatureGroupEngine at 0x7fa3f0114d10>,
 '_transformation_function_engine': <hsfs.core.transformation_function_engine.TransformationFunctionEngine at 0x7fa3f0841f10>,
 '_feature_view_engine': <hsfs.core.feature_view_engine.FeatureViewEngine at 0x7fa3f08407d0>,
 '_search_api': <hopsworks_common.core.search_api.SearchApi at 0x7fa3f0842390>}

In [10]:
import pandas as pd
# 2. Criar os dados de exemplo associados à entidade Pessoa
data = {
    "pessoa_id": [1001, 1002, 1003, 1004], # Chave primária (Primary Key)
    "idade": [28, 45, 32, 19],
    "gastos_30d": [1250.50, 4300.00, 890.20, 150.00],
    "media_saldo_6m": [3200.00, 12500.00, 2100.00, 400.00],
    "dias_desde_ultimo_login": [1, 5, 2, 0]
}

df_pessoa = pd.DataFrame(data)

In [21]:
import pandas as pd
# 2. Criar os dados de exemplo associados à entidade Pessoa
data = {
    "pessoa_id": [1001, 1002, 1003, 1004], # Chave primária (Primary Key)
    "peso": [110, 68, 90, 62],
    "time_futebol": ["palmeiras", "flamengo", "cruzeiro", "vasco"],
    "id_pais": ["Brasil", "Japao", "Espanha", "Brasil"],
    "quantos_dias_sem_comer": [1, 2, 4, 3]
}

df_identidade = pd.DataFrame(data)

df_financeiro = pd.DataFrame({
    "pessoa_id": [1001, 1002, 1003],
    "gastos_100d": [1200.0, 8500.0, 400.0],
    "inadimplente": [0, 0, 1] # Nosso Alvo (Target)
})

In [ ]:
df_pessoa

   pessoa_id  gastos_100d  inadimplente
0       1001       1200.0             0
1       1002       8500.0             0
2       1003        400.0             1

In [23]:
df_financeiro

   pessoa_id  gastos_100d  inadimplente
0       1001       1200.0             0
1       1002       8500.0             0
2       1003        400.0             1

In [ ]:
pessoa_fg = fs.get_or_create_feature_group(
    name="pessoa_comportamento_financeiro",
    version=1,
    primary_key=["pessoa_id"],
    description="Comportamento financeiro e de engajamento da entidade Pessoa",
    online_enabled=True # Habilita acesso de baixa latência para predições em tempo real
)

# Insert do DataFrame no Feature Store
pessoa_fg.insert(df_pessoa)

In [25]:
fg_identidade = fs.get_or_create_feature_group(
    name="pessoa_comportamento_identitario",
    version=1,
    primary_key=["pessoa_id"],
    online_enabled=True
)
fg_identidade.insert(df_identidade)

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/42213/fs/30898/fg/53307

Uploading Dataframe: 100.00% |██████████| Rows 4/4 | Elapsed Time: 00:01 | Remaining Time: 00:00

(None, None)

In [ ]:
fg_financeiro = fs.get_or_create_feature_group(
    name="pessoa_comportamento_financeiro_plus",
    version=1,
    primary_key=["pessoa_id"],
    online_enabled=True
)
fg_financeiro.insert(df_financeiro)

In [46]:
# Example: Read an existing feature group
fg_comportamento_financeiro = fs.get_feature_group(
    name="pessoa_comportamento_financeiro",
    version=1
)


fg_comportamento_identitario = fs.get_feature_group(
    name="pessoa_comportamento_identitario",
    version=1
)

fg_financeiro = fs.get_feature_group(
    name="pessoa_comportamento_financeiro_plus",
    version=1
)

In [ ]:
#propriedades da feature_group, existem outras (ver doc)
fg.columns
fg.description

[Feature('pessoa_id', 'bigint', None, True, False, False, 'bigint', None, 52432),
 Feature('idade', 'bigint', None, False, False, False, 'bigint', None, 52432),
 Feature('gastos_30d', 'double', None, False, False, False, 'double', None, 52432),
 Feature('media_saldo_6m', 'double', None, False, False, False, 'double', None, 52432),
 Feature('dias_desde_ultimo_login', 'bigint', None, False, False, False, 'bigint', None, 52432)]

'Comportamento financeiro e de engajamento da entidade Pessoa'

In [ ]:

# Read data from the feature group
df = fg.read()
print(f"Connected to {project.name}. Feature group has {len(df)} rows")

# For model serving
ms = project.get_model_serving()

# For model registry
mr = project.get_model_registry()

In [19]:
type(fg)

hsfs.feature_group.FeatureGroup

In [ ]:
fg

##  Feature View

In [39]:
all_fgs = fs.get_feature_groups()

In [47]:
for fg in all_fgs:
  print(f"Nome: {fg.name}, Versão: {fg.version}")

Nome: pessoa_comportamento_financeiro, Versão: 1
Nome: pessoa_comportamento_identitario, Versão: 1
Nome: pessoa_comportamento_financeiro_plus, Versão: 1

In [42]:
fg_comportamento_identitario.columns

[Feature('pessoa_id', 'bigint', None, True, False, False, 'bigint', None, 53307),
 Feature('peso', 'bigint', None, False, False, False, 'bigint', None, 53307),
 Feature('time_futebol', 'string', None, False, False, False, 'varchar(100)', None, 53307),
 Feature('id_pais', 'string', None, False, False, False, 'varchar(100)', None, 53307),
 Feature('quantos_dias_sem_comer', 'bigint', None, False, False, False, 'bigint', None, 53307)]

In [44]:
fg_comportamento_financeiro.columns

[Feature('pessoa_id', 'bigint', None, True, False, False, 'bigint', None, 52432),
 Feature('idade', 'bigint', None, False, False, False, 'bigint', None, 52432),
 Feature('gastos_30d', 'double', None, False, False, False, 'double', None, 52432),
 Feature('media_saldo_6m', 'double', None, False, False, False, 'double', None, 52432),
 Feature('dias_desde_ultimo_login', 'bigint', None, False, False, False, 'bigint', None, 52432)]

In [48]:
fg_financeiro.columns

[Feature('pessoa_id', 'bigint', None, True, False, False, 'bigint', None, 52433),
 Feature('gastos_100d', 'double', None, False, False, False, 'double', None, 52433),
 Feature('inadimplente', 'bigint', None, False, False, False, 'bigint', None, 52433)]

In [ ]:
query_features = fg_comportamento_financeiro.select(["idade", "dias_desde_ultimo_login"]) \
    .join(fg_financeiro.select(["gastos_100d", "inadimplente"])) \
        .join(fg_comportamento_identitario.select(["peso", "quantos_dias_sem_comer"]))

In [61]:
query_features.__dict__

{'_feature_store_name': 'my_first_project10_featurestore',
 '_feature_store_id': 30898,
 '_left_feature_group': <hsfs.feature_group.FeatureGroup at 0x7fa3f0128d10>,
 '_left_features': [Feature('idade', None, None, False, False, False, None, None, None),
  Feature('dias_desde_ultimo_login', None, None, False, False, False, None, None, None)],
 '_left_feature_group_start_time': None,
 '_left_feature_group_end_time': None,
 '_joins': [<hsfs.constructor.join.Join at 0x7fa386ba0cd0>,
  <hsfs.constructor.join.Join at 0x7fa386ba03d0>],
 '_filter': None,
 '_limit': None,
 '_lookback': None,
 '_python_engine': True,
 '_query_constructor_api': <hsfs.core.query_constructor_api.QueryConstructorApi at 0x7fa3f0116450>,
 '_storage_connector_api': <hsfs.core.storage_connector_api.StorageConnectorApi at 0x7fa386ba3910>,
 '_ambiguous_features_in_query': {}}

In [ ]:
query_features._left_features
query_features._left_feature_group.__dict__

[Feature('idade', None, None, False, False, False, None, None, None),
 Feature('dias_desde_ultimo_login', None, None, False, False, False, None, None, None)]

{'_version': 1,
 '_name': 'pessoa_comportamento_financeiro',
 '_event_time': None,
 '_online_enabled': True,
 '_location': 'hopsfs://rpc.namenode.service.consul:8020/apps/hive/warehouse/my_first_project10_featurestore.db/pessoa_comportamento_financeiro_1',
 '_id': 52432,
 '_subject': None,
 '_online_topic_name': 'my_first_project10_onlinefs',
 '_topic_name': None,
 '_notification_topic_name': None,
 '_deprecated': False,
 '_feature_store_id': 30898,
 '_feature_store': <hsfs.feature_store.FeatureStore at 0x7fa3f1091ed0>,
 '_variable_api': <hopsworks_common.core.variable_api.VariableApi at 0x7fa386bdf3d0>,
 '_alert_api': <hopsworks_common.core.alerts_api.AlertsApi at 0x7fa386bde850>,
 '_ttl': None,
 '_ttl_enabled': False,
 '_sink_enabled': False,
 '_missing_mandatory_tags': [],
 '_online_config': <hsfs.online_config.OnlineConfig at 0x7fa386bdf250>,
 '_data_source': <hsfs.core.data_source.DataSource at 0x7fa386bdf450>,
 '_multi_part_insert': False,
 '_embedding_index': None,
 '_expectation_suite': None,
 '_feature_group_engine': <hsfs.core.feature_group_engine.FeatureGroupEngine at 0x7fa3850f81d0>,
 '_statistics_engine': <hsfs.core.statistics_engine.StatisticsEngine at 0x7fa38c121790>,
 '_great_expectation_engine': <hsfs.core.great_expectation_engine.GreatExpectationEngine at 0x7fa386bdf350>,
 '_expectation_suite_engine': <hsfs.core.expectation_suite_engine.ExpectationSuiteEngine at 0x7fa386bdf190>,
 '_validation_report_engine': <hsfs.core.validation_report_engine.ValidationReportEngine at 0x7fa386bdf690>,
 '_validation_result_engine': <hsfs.core.validation_result_engine.ValidationResultEngine at 0x7fa3ef812350>,
 '_feature_monitoring_config_engine': <hsfs.core.feature_monitoring_config_engine.FeatureMonitoringConfigEngine at 0x7fa386bdf790>,
 '_feature_monitoring_result_engine': <hsfs.core.feature_monitoring_result_engine.FeatureMonitoringResultEngine at 0x7fa386bdfc50>,
 '_feature_store_name': 'my_first_project10_featurestore',
 '_description': 'Comportamento financeiro e de engajamento da entidade Pessoa',
 '_created': '2026-09-02T17:16:41.000Z',
 '_creator': User(email='ferreira.dfg@gmail.com', first_name='Diego', last_name='Gonçalves', href=None, username=None, status=0, secret=None, chosen_password=None, repeated_password=None, tos=False, two_factor=False, user_account_type=None, tours_state=0, max_num_projects=0, test_user=False, num_active_projects=0, num_remaining_projects=0, roles=[]),
 '_sink_job': None,
 '_sink_job_conf': None,
 '_features': [Feature('pessoa_id', 'bigint', None, True, False, False, 'bigint', None, 52432),
  Feature('idade', 'bigint', None, False, False, False, 'bigint', None, 52432),
  Feature('gastos_30d', 'double', None, False, False, False, 'double', None, 52432),
  Feature('media_saldo_6m', 'double', None, False, False, False, 'double', None, 52432),
  Feature('dias_desde_ultimo_login', 'bigint', None, False, False, False, 'bigint', None, 52432)],
 '_time_travel_format': 'DELTA',
 '_stream': False,
 '_parents': None,
 '_deltastreamer_jobconf': None,
 '_tags': None,
 '_materialization_job': None,
 '_primary_key': ['pessoa_id'],
 'foreign_key': [],
 '_partition_key': [],
 '_hudi_precombine_key': None,
 '_statistics_config': StatisticsConfig(True, False, False, False, [], kll=False, histogram_bins=None),
 '_offline_backfill_every_hr': None,
 '_vector_db_client': None,
 '_href': None,
 '_kafka_producer': None,
 '_feature_writers': None,
 '_writer': None,
 '_kafka_headers': None,
 '_transformation_functions': [],
 '_transformation_function_execution_dag': None}

In [50]:
feature_view = fs.create_feature_view(
    name="modelo_forecasting",
    version=1,
    labels=["inadimplente"],
    query=query_features
)

Feature view created successfully, explore it at
https://eu-west.cloud.hopsworks.ai:443/p/42213/fs/30898/fv/modelo_forecasting/version/1

In [51]:
feature_view

In [53]:
feauture_view = fs.get_feature_view(name="modelo_forecasting", version=1)

In [57]:
feature_view.__dict__
feature_view._query.__dict__

{'_name': 'modelo_forecasting',
 '_id': 30831,
 '_tags': [],
 '_query': <hsfs.constructor.query.Query at 0x7fa38c1be310>,
 '_featurestore_id': 30898,
 '_feature_store_id': 30898,
 '_feature_store_name': 'my_first_project10_featurestore',
 '_version': 1,
 '_description': '',
 '_labels': ['inadimplente'],
 '_inference_helper_columns': [],
 '_training_helper_columns': [],
 '_transformation_functions': [],
 '_features': [Training Dataset Feature('idade', 'bigint', 0, False, idade, 52432, None),
  Training Dataset Feature('dias_desde_ultimo_login', 'bigint', 1, False, dias_desde_ultimo_login, 52432, None),
  Training Dataset Feature('gastos_100d', 'double', 2, False, gastos_100d, 52433, None),
  Training Dataset Feature('inadimplente', 'bigint', 3, True, inadimplente, 52433, None),
  Training Dataset Feature('peso', 'bigint', 4, False, peso, 53307, None),
  Training Dataset Feature('quantos_dias_sem_comer', 'bigint', 5, False, quantos_dias_sem_comer, 53307, None)],
 '_request_parameters': None,
 '_feature_view_engine': <hsfs.core.feature_view_engine.FeatureViewEngine at 0x7fa42fe2df50>,
 '_transformation_function_engine': <hsfs.core.transformation_function_engine.TransformationFunctionEngine at 0x7fa3f0b83790>,
 '_FeatureView__vector_server': None,
 '_FeatureView__batch_scoring_server': None,
 '_FeatureView__fully_qualified_primary_keys': None,
 '_FeatureView__fully_qualified_event_time': None,
 '_serving_keys': [{"feature_name": "pessoa_id", "join_index": 0, "feature_group_id": 52432, "_feature_group_name": "pessoa_comportamento_financeiro", "feature_group_version": 1, "required": true, "prefix": "", "join_on": null},
  {"feature_name": "pessoa_id", "join_index": 1, "feature_group_id": 52433, "_feature_group_name": "pessoa_comportamento_financeiro_plus", "feature_group_version": 1, "required": false, "prefix": "", "join_on": "pessoa_id"},
  {"feature_name": "pessoa_id", "join_index": 2, "feature_group_id": 53307, "_feature_group_name": "pessoa_comportamento_identitario", "feature_group_version": 1, "required": false, "prefix": "", "join_on": "pessoa_id"}],
 '_prefix_serving_key_map': {},
 '_primary_keys': set(),
 '_vector_db_client': None,
 '_statistics_engine': <hsfs.core.statistics_engine.StatisticsEngine at 0x7fa386ba1b50>,
 '_logging_enabled': False,
 '_feature_logging': None,
 '_alert_api': <hopsworks_common.core.alerts_api.AlertsApi at 0x7fa386b7ac50>,
 '_missing_mandatory_tags': [],
 '_extra_log_columns': None,
 '_last_accessed_training_dataset': None,
 '_feature_logger': None,
 '_serving_training_dataset_version': None,
 '_transformation_n_processes': None,
 '_FeatureView__label_column_names': None,
 '_FeatureView__transformed_feature_names': None,
 '_FeatureView__untransformed_feature_names': None,
 '_FeatureView__required_serving_key_names': None,
 '_FeatureView__root_feature_group_event_time_column_name': None,
 '_FeatureView__extra_logging_column_names': None,
 '_on_demand_transformation_execution_graph': None,
 '_FeatureView__on_demand_transformation_functions': None,
 '_model_dependent_transformation_execution_graph': <hsfs.core.transformation_execution_dag.TransformationExecutionDAG at 0x7fa3f0ba0250>,
 '_feature_monitoring_config_engine': <hsfs.core.feature_monitoring_config_engine.FeatureMonitoringConfigEngine at 0x7fa3ef812cd0>,
 '_feature_monitoring_result_engine': <hsfs.core.feature_monitoring_result_engine.FeatureMonitoringResultEngine at 0x7fa38c1ea410>}

{'_feature_store_name': 'my_first_project10_featurestore',
 '_feature_store_id': 30898,
 '_left_feature_group': <hsfs.feature_group.FeatureGroup at 0x7fa3f01298d0>,
 '_left_features': [Feature('idade', 'bigint', None, False, False, False, None, None, 52432),
  Feature('dias_desde_ultimo_login', 'bigint', None, False, False, False, None, None, 52432)],
 '_left_feature_group_start_time': None,
 '_left_feature_group_end_time': None,
 '_joins': [<hsfs.constructor.join.Join at 0x7fa38c1bced0>,
  <hsfs.constructor.join.Join at 0x7fa3e4659990>],
 '_filter': None,
 '_limit': None,
 '_lookback': None,
 '_python_engine': True,
 '_query_constructor_api': <hsfs.core.query_constructor_api.QueryConstructorApi at 0x7fa3f0129190>,
 '_storage_connector_api': <hsfs.core.storage_connector_api.StorageConnectorApi at 0x7fa3f0128290>,
 '_ambiguous_features_in_query': {}}

In [59]:
feature_view._query._left_features

[Feature('idade', 'bigint', None, False, False, False, None, None, 52432),
 Feature('dias_desde_ultimo_login', 'bigint', None, False, False, False, None, None, 52432)]